name: Python Style Check

on:
  pull_request:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run flake8 on diff
        run: |
          flake8 ./portfolio/ --count --show-source --max-complexity=10 --max-line-length=120 --statistics

      - name: Check with black on diff
        run: black --check --diff --line-length 120 ./portfolio/

      - name: Check imports with isort on diff
        run: isort --check-only --diff -m VERTICAL_GRID --line-length 120 ./portfolio/
