name: Python Style Check

on:
  push:
    branches: [ '**' ] # Triggers on push to any branch
  pull_request:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort diff-cover

      - name: Run flake8 on diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.patch
          diff-quality --violations=flake8 diff.patch

      - name: Check with black  on diff
        run: black --check --diff .

      - name: Check imports with isort  on diff
        run: isort --check-only --diff .
